SJRConstructions.Web/Controllers/InvitationController.cs
using System.Text;
using AutoMapper;
using SJRConstructions.Core.Entities;
using SJRConstructions.Core.Interfaces;
using SJRConstructions.Web.Enums;
using SJRConstructions.Web.Services.EmailService;
using SJRConstructions.Web.Services.User;
using SJRConstructions.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace SJRConstructions.Web.Controllers
{
    public class InvitationController : Controller
    {
        private readonly IEmailSender _emailSender;
        private readonly IMapper mapper;
        private readonly IEmailRepository emailRepository;
        private readonly IConfiguration configuration;
        private readonly IUserRepository _userRepository;
        private readonly IUserService _userService;
        private UserProfile UserData;

        public InvitationController(IEmailSender emailSender, IMapper mapper, IEmailRepository emailRepository, IConfiguration configuration,
            IUserRepository userRepository,IUserService userService) {
            this._emailSender = emailSender;
            this.mapper = mapper;
            this.emailRepository = emailRepository;
            this.configuration = configuration;
            _userRepository = userRepository;
            _userService = userService;
            UserData = _userService.GetCurrentUser();
        }
        public IActionResult Index()
        {
            if (UserData == null)
            {                
                return RedirectToAction("Login", "User");
            }        
            UserRole userRole = (UserRole)UserData.RoleID;
            if (userRole == UserRole.TroopCoordinator)
            {
                TempData["AccessMessage"] = "You dont have permission to access the Page.";
                return View("NoPermissions");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Invite(InvitationVM invitationVM)
       {
            if(ModelState.IsValid)
            {

                invitationVM.InviteToken = Guid.NewGuid().ToString();
                invitationVM.Type = "RegistrationInvite";
                var invitation = mapper.Map<EmailService>(invitationVM);
                await emailRepository.SaveInvitationAsync(invitation);


                string invitationEmail = invitation.Email;           

                if(!string.IsNullOrWhiteSpace(invitationEmail))
                { 

                    StringBuilder registerEmailBody = GetEmailContent(invitationVM.InviteToken);           
                                   
                    var message = new Message(new string[] { invitationEmail }, "Register for Girl Scout Cookie Booth", registerEmailBody.ToString(), null);
                    await _emailSender.SendEmailAsync(message);                    
                    TempData["successMessage"] = "Registration invitation sent successfully";
                }
            }
            return RedirectToAction(nameof(Index));            
        }
        private StringBuilder GetEmailContent(string token)
        {
            string registerLink = configuration.GetValue<string>("UserInformation:InvitationLink") + token;
            TempData["registrationLink"] = registerLink;
            StringBuilder emailBody = new StringBuilder();
            emailBody.Append("<h2>Registration Invitation</h2>");
            emailBody.Append("<p>You are invited to register for Girl Scout Cookie Booth. Click on the below link to register.</p>");
            emailBody.Append("<a href='" + registerLink + "'>Register Cookie Booth</a>");
            emailBody.Append("<br/><br/>");
            emailBody.Append("Thank you,<br/>");
            emailBody.Append("Girl Scout Cookie Booth Team");
            return emailBody;
        }
    }
}

SJRConstructions.Web/Controllers/ProjectController.cs
using AutoMapper;
using SJRConstructions.Core.Entities;
using SJRConstructions.Core.Interfaces;
using SJRConstructions.Web.Enums;
using SJRConstructions.Web.Services.User;
using SJRConstructions.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace SJRConstructions.Web.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IMapper mapper;
        private readonly IUserRepository _userRepository;
        private readonly IProjectRepository _projectRepository;
        private readonly IUserService _userService;
        private UserProfile UserData;

        public ProjectController(IMapper mapper, IUserService userService, IUserRepository userRepository, IProjectRepository projectRepository)
        {
            this.mapper = mapper;
            _userService = userService;
            UserData = _userService.GetCurrentUser();
            _userRepository = userRepository;
            _projectRepository = projectRepository;
        }
        public async Task<IActionResult> Index()
        {
            if (UserData == null)
            {
                return RedirectToAction("Login", "User");
            }
            UserRole userRole = (UserRole)UserData.RoleID;
            if (userRole == UserRole.TroopCoordinator)
            {
                TempData["AccessMessage"] = "You dont have permission to access the Page.";
                return View("NoPermissions");
            }
            var projectDetails = mapper.Map<List<ProjectDetailsVM>>(await _projectRepository.GetAllProjects());

            return View(projectDetails);
        }

        public async Task<IActionResult> Create()
        {
            if (UserData == null)
            {
                return RedirectToAction("Login", "User");
            }
            UserRole userRole = (UserRole)UserData.RoleID;
            if (userRole == UserRole.TroopCoordinator)
            {
                TempData["AccessMessage"] = "You dont have permission to access the Page.";
                return View("NoPermissions");
            }
            ProjectDetailsVM projectDetailsVM = new ProjectDetailsVM();
            return View(projectDetailsVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProjectDetailsVM projectVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Map the ViewModel to the corresponding entity
                    var project = mapper.Map<ProjectDetails>(projectVM);
                    //project.StatusId = projectVM.Status;
                    // Save the project entity to the database
                    var result = await _projectRepository.CreateLocationAsync(project);

                    // Assuming projectRepository.CreateProjectAsync returns the created project
                     if (result != null)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Failed to create project.");
                    }
                }
            }
            catch (Exception ex)
            {
                // Log the exception or handle it appropriately
                ModelState.AddModelError(string.Empty, "An error occurred while creating the project.");
                return View(projectVM);
            }
            return View(projectVM);
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (UserData == null)
            {
                return RedirectToAction("Login", "User");
            }
            UserRole userRole = (UserRole)UserData.RoleID;
            if (userRole == UserRole.TroopCoordinator)
            {
                TempData["AccessMessage"] = "You dont have permission to access the Page.";
                return View("NoPermissions");
            }
            if (id == null)
            {
                return NotFound();
            }
            var project = await _projectRepository.GetProjectsById(id);
            if (project == null)
            {
                return NotFound();
            }
            var projectDetails = mapper.Map<ProjectDetailsVM>(project);

            return View(projectDetails);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProjectDetailsVM projectVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Map the ViewModel to the corresponding entity
                    var project = mapper.Map<ProjectDetails>(projectVM);
                    //project.StatusId = projectVM.Status;
                    // Save the project entity to the database
                    var result = await _projectRepository.UpdateLocationAsync(project);

                    // Assuming projectRepository.CreateProjectAsync returns the created project
                    if (result != null)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Failed to create project.");
                    }
                }
            }
            catch (Exception ex)
            {
                // Log the exception or handle it appropriately
                ModelState.AddModelError(string.Empty, "An error occurred while creating the project.");
                return View(projectVM);
            }
            return View(projectVM);
        }

    }
}

SJRConstructions.Web/Views/Shared/NoPermissions.cshtml
@page
@using SJRConstructions.Web.Views;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>No Permission</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f8f9fa;
            text-align: center;
        }

        h1 {
            margin-bottom: 20px;
        }

        .btn {
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <h1>No Permission</h1>
        <p class="lead">@TempData["AccessMessage"]</p>
        <a href="/" class="btn btn-primary">Go to Home</a>
    </div>
</body>
</html>

SJRConstructions.Web/Views/Shared/_ConfirmMessagepopup.cshtml
<div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmation</h5>
                @*<button type="button" class="close btn-danger" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>*@
            </div>
            <div class="modal-body">
                <div id="cfrsavemessage" style="display:none">Are you sure you want to submit?</div>
                <div id="cfrresetmessage" style="display:none">Are you sure you want to reset the changes?</div>
                <div id="cfrdeletemessage" style="display:none">Are you sure you want to delete the changes?</div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" id="closebtn" data-dismiss="modal"><i class="fa-solid fa-xmark me-1"></i> Close</button>
                <button type="button" style="display:none" class="btn btn-primary" id="saveChangesBtn"><i class="fa-solid fa-floppy-disk me-1"></i> Save</button>
                <button type="button" style="display:none" class="btn btn-primary" id="resetBtn"><i class="fa-solid fa-arrow-rotate-left me-1"></i> Reset</button>
                <button type="button" style="display:none" class="btn btn-primary" id="crfdeleteBtn"><i class="fa-solid fa-arrow-rotate-left me-1"></i> Delete</button>
            </div>
        </div>
    </div>
</div>
<button id="showCrfMessageModal" style="display: none;" data-toggle="modal" data-target="#confirmationModal"></button>
<script>
        // Add this script to set focus on the close button when the modal is shown
    $('#confirmationModal').on('shown.bs.modal', function () {
            $('#closebtn').focus();
        });
    </script>
<style>
    #saveChangesBtn, #resetBtn, #crfdeleteBtn, #closebtn{
        border-radius: 25px;
    }
</style>

SJRConstructions.Web/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Use roleId as needed in the layout -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Girl Scouts Cookie Booth</title>
    <!-- Load CSS files -->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SJRConstructions.Web.styles.css" asp-append-version="true" />
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Include Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Load JS files -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js" type="text/javascript"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <script src="~/js/messagemodalpopup.js"></script>
    <style>
        html, body {
            font-family: "Palatino Linotype", "Book Antiqua", Palatino, serif !important;
        }
    </style>
</head>

<body style="background-image: url('/assets/backround.jpg'); background-size: cover; background-repeat: no-repeat;">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between border-bottom fixed-top bg-light">
        <div class="col-md-3 mb-2 mb-md-0">
            <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
                <img src="/assets/sjrlogo.jpg" style="max-width: 130px; height: auto;" alt="Girl Scout Logo">
                <div class="vr me-1 ms-1 mt-1" style="height: 50px; color: #ccc; border: solid 1.5px"></div>
                @*<img src="/assets/Dell_Technologies_logo.png" style="height: 23px; padding: 0; width: 182px; margin-top: 20px" alt="dell logo">*@
            </a>
        </div>
        @if (User.Identity.IsAuthenticated)
        {
            <ul class="nav col-9 col-md-auto mb-2 justify-content-center mb-md-0">

                <li>
                    <a class="nav-link px-2" asp-area="" asp-controller="Home" asp-action="Index">
                        <i class="fa-solid fa-house-chimney me-1"></i> Home
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" href="#" role="button" data-bs-toggle="dropdown">
                        <i class="fa-solid fa-calendar-days me-1"></i> Masters
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li>
                            <a class="dropdown-item" asp-area="" asp-controller="Project" asp-action="Index" id="eventnav">
                                <i class="fa-regular fa-calendar-plus me-1"></i> Projects
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" asp-area="" asp-controller="EventManagement" asp-action="Index" id="eventdetailsnav">
                                <i class="fa-brands fa-elementor me-1"></i> Footing Options
                            </a>
                        </li>
                    </ul>
                </li>

            </ul>

            <div class="col-3 text-end">
                <ul class="nav justify-content-end">
                    <li class="nav-item dropdown">

                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" href="#" role="button" data-bs-toggle="dropdown">
                            <i class="fa-solid fa-circle-user"></i> @User.FindFirst(ClaimTypes.Email)?.Value
                        </a>

                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Profile">
                                <i class="fa-solid fa-user-pen me-1"></i> Profile
                            </a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">
                                <i class="fa-solid fa-lock me-1"></i> Sign Out
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        }
        else
        {
            <div class="col-md-3 text-end">
                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">
                    <i class="fa-solid fa-user-large me-1" style="color: #00b451;"></i> Sign In
                </a>
            </div>
        }
    </header>
    <div class="container-fluid" style="margin-top:80px;">
        <main role="main" class="pb-3">
            <div class="formclass">
                @RenderBody()
                @Html.Partial("_Messagemodalpopup")
                @Html.Partial("_Loader")
                @Html.Partial("_ConfirmMessagepopup")
            </div>
        </main>
    </div>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SJRConstructions.Web/Views/Shared/_Layout1.cshtml
@using System.Security.Claims;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Girl Scouts Cookie Booth</title>
    <!-- Load CSS files -->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SJRConstructions.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css">
    <!-- Include Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Load JS files -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js" type="text/javascript"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js"></script>
    <script src="~/js/messagemodalpopup.js"></script>

    <style>
        html, body {
            font-family: "Palatino Linotype", "Book Antiqua", Palatino, serif !important;
        }
    </style>

</head>
<body style="background-image: url('/assets/backround.jpg'); background-size: cover; background-repeat: no-repeat;">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between border-bottom fixed-top bg-light">
        <div class="col-md-3 mb-2 mb-md-0">
            <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none mx-4">
                <img src="/assets/sjrlogo.jpg" style="max-width: 130px; height: auto;" alt="Girl Scout Logo">
            </a>
        </div>
        @if (User.Identity.IsAuthenticated)
        {
            <ul class="nav col-9 col-md-auto mb-2 justify-content-center mb-md-0">
                @if (User.FindFirst(ClaimTypes.Role)?.Value == "TroopCoordinator")
                {
                    <li>
                        <a class="nav-link px-2" asp-area="" asp-controller="Home" asp-action="Index">
                            <i class="fa-solid fa-house-chimney me-1"></i> Home
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" href="#" role="button" data-bs-toggle="dropdown">
                            <i class="fa-solid fa-calendar-days me-1"></i> Events
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li>
                                <a class="dropdown-item" asp-area="" asp-controller="Lottery" asp-action="LotterySelection" id="preferencenav">
                                    <i class="fa-solid fa-bookmark me-1"></i> Step 1 : Submit Shift Preferences
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" asp-area="" asp-controller="Lottery" asp-action="SelectedPreferenceList" id="preferencelistnav">
                                    <i class="fa-solid fa-list-check me-1"></i> Step 2 : Submitted Preference List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="nav-link px-2" asp-area="" asp-controller="Lottery" asp-action="Result">
                            <i class="fa-solid fa-dice me-1"></i> Lottery Results
                        </a>
                    </li>
                }
                else
                {
                    <li>
                        <a class="nav-link px-2" asp-area="" asp-controller="Home" asp-action="Index">
                            <i class="fa-solid fa-house-chimney me-1"></i> Home
                        </a>
                    </li>
                    <li>
                        <a class="nav-link px-2" asp-area="" asp-controller="Invitation" asp-action="Index">
                            <i class="fa-solid fa-envelope me-1"></i> Invitation
                        </a>
                    </li>
                    <li>
                        <a class="nav-link px-2" asp-area="" asp-controller="Location" asp-action="Index">
                            <i class="fa-solid fa-location-dot me-1"></i> Locations
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" href="#" role="button" data-bs-toggle="dropdown">
                            <i class="fa-solid fa-calendar-days me-1"></i> Events
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li>
                                <a class="dropdown-item" asp-area="" asp-controller="EventManagement" asp-action="Event" id="eventnav">
                                    <i class="fa-regular fa-calendar-plus me-1"></i> Event Creation & Generate Shifts
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" asp-area="" asp-controller="EventManagement" asp-action="Index" id="eventdetailsnav">
                                    <i class="fa-brands fa-elementor me-1"></i> Event Details
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" asp-area="" asp-controller="Lottery" asp-action="UnclaimedShift" id="unclaimedshiftnav">
                                    <i class="fa-solid fa-circle-exclamation me-1"></i> Unclaimed Shift
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="nav-link px-2" asp-area="" asp-controller="Lottery" asp-action="AssignShifts">
                            <i class="fa-solid fa-check-double me-1"></i> Assign Shifts
                        </a>
                    </li>
                    <li>
                        <a class="nav-link px-2" asp-area="" asp-controller="Lottery" asp-action="Result">
                            <i class="fa-solid fa-dice me-1"></i> Lottery Results
                        </a>
                    </li>
                }
            </ul>

            <div class="col-3 text-end">
                <ul class="nav justify-content-end">
                    <li class="nav-item dropdown">

                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" href="#" role="button" data-bs-toggle="dropdown">
                            <i class="fa-solid fa-circle-user me-1"></i> @User.FindFirst(ClaimTypes.Email)?.Value
                        </a>

                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Profile">
                                <i class="fa-solid fa-user-pen me-1"></i> Profile
                            </a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">
                                <i class="fa-solid fa-lock me-1"></i> Sign Out
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        }
        else
        {
            <div class="col-md-3 text-end">
                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">
                    <i class="fa-solid fa-user-large me-1" style="color: #00b451;"></i> Sign In
                </a>
            </div>
        }
    </header>

    <div class="container-fluid">
        <main role="main" class="pb-3" style="margin-top:80px;">
            <div class="formclass">
                @RenderBody()
                @Html.Partial("_Messagemodalpopup")
                @Html.Partial("_Loader")
                @Html.Partial("_ConfirmMessagepopup")
            </div>
        </main>
    </div>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SJRConstructions.Web/Views/Shared/_Loader.cshtml
@*<link href="~/css/site.css" rel="stylesheet" />*@
<div id="loader" class="loader-wrapper">
    <div class="loader"></div>
    <div class="loader-text">Saving...</div>
</div>
<script>
function showLoader() {
    document.getElementById('loader').style.display = 'flex'; // Show the loader
}

function hideLoader() {
    document.getElementById('loader').style.display = 'none'; // Hide the loader
}
</script>

SJRConstructions.Web/Views/Shared/_Messagemodalpopup.cshtml
<!-- Single Message Modal -->
<div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="messageModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="messageModalLabel">Message</h5>
                <button type="button" class="close btn-danger" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="messageContent"></div>
            </div>
        </div>
    </div>
</div>

<!-- Button trigger for the modal -->
<button id="showMessageModal" style="display: none;" data-toggle="modal" data-target="#messageModal"></button>